// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(HackboxDbContext))]
    [Migration("20260213075554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Entities.AuthSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("SessionId");

                    b.HasIndex("Username");

                    b.ToTable("auth_sessions");
                });

            modelBuilder.Entity("Api.Data.Entities.ChallengeTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_number");

                    b.Property<int>("Seconds")
                        .HasColumnType("integer")
                        .HasColumnName("seconds");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.HasIndex("TeamName", "ChallengeNumber")
                        .IsUnique();

                    b.ToTable("challenge_times");
                });

            modelBuilder.Entity("Api.Data.Entities.TeamProgressEntity", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_id");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TeamId");

                    b.ToTable("team_progress");
                });

            modelBuilder.Entity("Api.Data.Entities.TimerStateEntity", b =>
                {
                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.Property<int>("ManualTimerAccumulatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("manual_timer_accumulated_seconds");

                    b.Property<DateTime?>("ManualTimerStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manual_timer_started_at");

                    b.Property<string>("ManualTimerStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("manual_timer_status");

                    b.Property<DateTime?>("TimerStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timer_started_at");

                    b.HasKey("TeamName");

                    b.ToTable("timer_states");
                });

            modelBuilder.Entity("Api.Data.Entities.ChallengeTimeEntity", b =>
                {
                    b.HasOne("Api.Data.Entities.TimerStateEntity", "TimerState")
                        .WithMany("ChallengeTimes")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimerState");
                });

            modelBuilder.Entity("Api.Data.Entities.TimerStateEntity", b =>
                {
                    b.Navigation("ChallengeTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
